topics:
  - mathematics
  - education
  - python
  - gui
  - pyside6
  - arxiv
  - mit-ocw
  - project-gutenberg
  - pdf-downloader
  - textbooks
  - lecture-notes
  - math-resources
  - educational-resources
  - document-management
  - academic-tools 